# site settings
title: On Gods and Sages
subtitle: A blog on the spirit
email: raja@thekollurus.com
description: Some travelogues to Spiritual places + religious ruminations by a soul in search of peace
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Raja Shankar Kolluru
street_address: Somewhere out there
city: Bangalore
state: KA
zip_code: 
country: India
phone: 

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

menus:
  - Home: "/"
  - Musings: "/category/001-musings.html"
  - Ethics: "/category/002-ethics.html"
  - History: "/category/003-history.html"
  - Time: "/category/004-time.html"
  - Kedar And Badri: "/category/005-himalayan-travels-2015.html"
  - Mada Maheshwar: "/category/006-himalayan-travels-2018.html"
  - Kumbh 2025: "/category/007-kumbh-2025.html"
  

sass:
  style: compressed
